#!/bin/sh

echo "Running client up script..."

if [ "${PEER_DNS}" != "no" ]; then
        NS=
        DOMAIN=
        SEARCH=
        NAMES=
        i=1
        while true ; do
                eval opt=\$foreign_option_${i}
                echo "Mangling $opt"
                [ -z "${opt}" ] && break
                if [ "${opt}" != "${opt#dhcp-option DOMAIN *}" ] ; then
                        if [ -z "${DOMAIN}" ] ; then
                                DOMAIN="${opt#dhcp-option DOMAIN *}"
                        else
                                SEARCH="${SEARCH}${SEARCH:+ }${opt#dhcp-option DOMAIN *}"
                        fi
                elif [ "${opt}" != "${opt#dhcp-option DNS *}" ] ; then
                        NS="${NS}nameserver ${opt#dhcp-option DNS *}\n"

                elif [ "${opt}" != "${opt#dhcp-option name *}" ] ; then
                    NAME=$(echo ${opt} | cut -d' ' -f3)
                    IP=$(echo $NAME | cut -d: -f2)
                    NAME=$(echo $NAME | cut -d: -f1)
                    NAMES="${NAMES}$IP\t$NAME\n"
                fi
                i=$((${i} + 1))
        done

        if [ -n "${NS}" ] ; then
                DNS="# Generated by openvpn for interface ${dev}\n"
                if [ -n "${SEARCH}" ] ; then
                        DNS="${DNS}search ${DOMAIN} ${SEARCH}\n"
                elif [ -n "${DOMAIN}" ]; then
                        DNS="${DNS}domain ${DOMAIN}\n"
                fi
                DNS="${DNS}${NS}"
                if [ -x /sbin/resolvconf ] ; then
                        printf "${DNS}" | /sbin/resolvconf -a "${dev}"
                else
                        # Preserve the existing resolv.conf
                        if [ -e /etc/resolv.conf ] ; then
                                cp /etc/resolv.conf /etc/resolv.conf-"${dev}".sv
                        fi
                        printf "${DNS}" > /etc/resolv.conf
                        chmod 644 /etc/resolv.conf
                fi
        fi

        if [ -n "${NAMES}" ]; then
            printf "\n${NAMES}" >> /etc/hosts;
        fi
fi

# Below section is Gentoo specific
# Quick summary - our init scripts are re-entrant and set the SVCNAME env var
# as we could have >1 openvpn service

if [ -n "${SVCNAME}" ]; then
        # If we have a service specific script, run this now
        if [ -x /etc/openvpn/"${SVCNAME}"-up.sh ] ; then
                /etc/openvpn/"${SVCNAME}"-up.sh "$@"
        fi

        # Re-enter the init script to start any dependant services
        if ! /etc/init.d/"${SVCNAME}" --quiet status ; then
                export IN_BACKGROUND=true
                /etc/init.d/${SVCNAME} --quiet start
        fi
fi

exit 0
