# docker-compose for nfs-client
#
version: "2.4"
services:

  some-client:
    network_mode: service:openvpn-client
    image: byrnedo/alpine-curl
    depends_on:
      openvpn-client:
        condition: service_healthy

  another-client:
    networks:
      - vpn-client
    image: byrnedo/alpine-curl
    links:
      - "openvpn-client:port-forwarded-to-some-server"
    depends_on:
      openvpn-client:
        condition: service_healthy

  yet-another-client:
    networks:
      - vpn-client-2
    image: byrnedo/alpine-curl
    links:
      - "openvpn-client:port-forwarded-to-some-server"
    depends_on:
      openvpn-client:
        condition: service_healthy

  openvpn-client:
    image: phlax/openvpn-client
    ports:
      - 8080
      - 8081
    depends_on:
      openvpn-server:
        condition: service_healthy
    cap_add:
      - NET_ADMIN
    networks:
      vpn-in-between:
      vpn-client:
        ipv4_address: 10.23.23.2
      vpn-client-2:
        ipv4_address: 10.23.24.2
    volumes:
      - ${PWD}/example/client:/etc/openvpn/client
      - /dev/net:/dev/net:z
    environment:
      - VPN_CLIENT_NAME=vpn-client
      - VPN_SERVER_HOST=openvpn-server
      - VPN_SERVER_PORT=1194
      - OVPN_PORT_FORWARDS=10.23.23.2:8080:some-server:80 10.23.24.2:8080:some-server:80 10.23.24.2:8081:some-server:80
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      test: ["CMD-SHELL", "ip addr show dev tun0"]

  openvpn-server:
    image: phlax/openvpn-server
    depends_on:
      some-server:
        condition: service_started
    cap_add:
      - NET_ADMIN
    networks:
      - some-server-network
      - vpn-in-between
    volumes:
      - ${PWD}/example/server:/etc/openvpn/server
    environment:
      - OPENVPN_DNS_NAMES=some-server some-other-server
      - VPN_SERVER_NAME=openvpn-server.ex.ample
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      test: ["CMD-SHELL", "ip addr show dev tun0"]

  some-server:
    image: nginx
    networks:
    - some-server-network
    volumes:
    - ${PWD}/example/nginx/conf.d:/etc/nginx/conf.d
    - ${PWD}/example/nginx/index.html:/usr/share/nginx/html/index.html

networks:
  vpn-in-between:
  some-server-network:
  vpn-client:
    ipam:
      config:
      - subnet: 10.23.23.0/24
  vpn-client-2:
    ipam:
      config:
      - subnet: 10.23.24.0/24
