# docker-compose for phlax/openvpn-client
#
version: "2.4"
services:

  openvpn-client:
    privileged: true
    image: phlax/openvpn-client
    build:
      context: ./docker/openvpn-client

  openvpn-server:
    privileged: true
    image: phlax/openvpn-server
    build:
      context: ./docker/openvpn-server
