#!/bin/bash

if [ ! -z "$TRAP_ERRORS" ]; then
    trap "$TRAP_ERRORS" ERR
fi

docker-compose run --rm side0-client0 -m2 http://side1-server0 > response.txt
cat response.txt
docker-compose logs side1-server0


docker-compose run --rm side0-client1 -m2 http://port-forwarded-to-side1-server0:8080 > response.txt
cat response.txt
docker-compose logs side1-server0


docker-compose run --rm side0-client2 -m2 http://port-forwarded-to-side1-server0:8080 > response.txt
cat response.txt
docker-compose logs side1-server0


docker-compose run --rm side0-client2 -m2 http://port-forwarded-to-side1-server0:8081 > response.txt
cat response.txt
docker-compose logs side1-server0


docker-compose run -T --rm side1-client0 -m5 http://side0-server0 | grep Hello
docker-compose logs side0-server0
