#!/bin/bash

if [ ! -z "$TRAP_ERRORS" ]; then
    trap "$TRAP_ERRORS" ERR
fi

# stop the vpn client and check the daemon exited properly
docker-compose stop openvpn-client
docker-compose logs openvpn-client

# stop the vpn server and check the daemon exited properly
docker-compose stop openvpn-server
docker-compose logs openvpn-server

# all gone
docker-compose ps
