#!/bin/bash

if [ ! -z "$TRAP_ERRORS" ]; then
    trap "$TRAP_ERRORS" ERR
fi

# stop the vpn client and check the daemon exited properly
docker-compose stop vpn-side0
docker-compose logs vpn-side0

# stop the vpn server and check the daemon exited properly
docker-compose stop vpn-side1
docker-compose logs vpn-side1

# all gone
docker-compose ps
