#!/bin/sh

OPTIONS=$1
DNS_NAMES=$(cat /etc/openvpn/dns-names)

if [ ! -z "$DNS_NAMES" ]; then
    set -- junk $DNS_NAMES
    shift
    for NAME; do
        ADDRESS=$(getent hosts $NAME | awk '{ print $1 }')
        if [ ! -z "$ADDRESS" ]; then
            echo "Adding name forwarding for: $NAME -> $ADDRESS"
            echo "push \"dhcp-option name $NAME:$ADDRESS\"" >> $OPTIONS
	    echo "Adding route to $NAME -> $ADDRESS"
	    echo "push \"route $ADDRESS 255.255.255.255\"" >> $OPTIONS
        else
            echo "Unable to resolve address for $NAME"
        fi
    done
else
    echo 'Not adding any $DNS_NAMES, as none specified'
fi
